// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79EUlTi1hUD-M3PSZJrKySJhrCvxPF1U',
    appId: '1:474356139139:web:a67d2a6bc2cdcf174c07b6',
    messagingSenderId: '474356139139',
    projectId: 'learn-flutter-firebase-c23fb',
    authDomain: 'learn-flutter-firebase-c23fb.firebaseapp.com',
    storageBucket: 'learn-flutter-firebase-c23fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5-XfBHRUWZB5NP9S5Y3FsTZh4rIUugoE',
    appId: '1:474356139139:android:972b77e53f6bda314c07b6',
    messagingSenderId: '474356139139',
    projectId: 'learn-flutter-firebase-c23fb',
    storageBucket: 'learn-flutter-firebase-c23fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl_mimmXuI2B5dW-OPZlSQmO-C2UziBBA',
    appId: '1:474356139139:ios:c8854557e58ce18b4c07b6',
    messagingSenderId: '474356139139',
    projectId: 'learn-flutter-firebase-c23fb',
    storageBucket: 'learn-flutter-firebase-c23fb.appspot.com',
    iosBundleId: 'com.example.learnFlutterAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl_mimmXuI2B5dW-OPZlSQmO-C2UziBBA',
    appId: '1:474356139139:ios:c8854557e58ce18b4c07b6',
    messagingSenderId: '474356139139',
    projectId: 'learn-flutter-firebase-c23fb',
    storageBucket: 'learn-flutter-firebase-c23fb.appspot.com',
    iosBundleId: 'com.example.learnFlutterAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC79EUlTi1hUD-M3PSZJrKySJhrCvxPF1U',
    appId: '1:474356139139:web:0bfbfd972a5297424c07b6',
    messagingSenderId: '474356139139',
    projectId: 'learn-flutter-firebase-c23fb',
    authDomain: 'learn-flutter-firebase-c23fb.firebaseapp.com',
    storageBucket: 'learn-flutter-firebase-c23fb.appspot.com',
  );
}
